language: shell
dist: xenial
sudo: required
os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-8
    packages:
    - unzip
    - gawk
    - wget
    - git
    - perl
    - clang-8
    - libexpat-dev
    - libpcre3-dev
    - libxml2-dev
    - libxslt-dev
    - libgeoip-dev
    - libgd-dev
    - libpam0g-dev
    - libperl-dev
    - uuid-dev
    - debhelper
    - golang
    - cmake
    - libunwind-dev
jobs:
  include:
    - stage: nginx-huihui
      script:
      - mkdir -p releases/$TRAVIS_JOB_NUMBER
      - cd nginx-build
      - sh ./require.sh
      - sh ./build.sh
      - cp -r debian nginx-1*/
      - cd nginx-1*
      - sudo dpkg-buildpackage -b -uc
      - cd ..
      - sudo chmod -R 777 nginx-1* *.deb
      - ls -alh *.deb
      - cp *.deb ../releases/$TRAVIS_JOB_NUMBER
      - sudo cp ./luajit2-*/src/libluajit.so /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
      - sudo ldconfig
      - ./nginx-1*/objs/nginx -V
      - file ./nginx-1*/objs/nginx
      - ldd ./nginx-1*/objs/nginx
      - cd ..
      deploy: &s3
        provider: s3
        access_key_id: "$ACCESS_KEY_ID"
        secret_access_key: "$SECRET_ACCESS_KEY"
        bucket: my-scripts-releases
        skip_cleanup: true
        local_dir: releases
        endpoint: https://storage.huihui.cat
    - stage: nginx-boringssl-huihui
      script:
      - mkdir -p releases/$TRAVIS_JOB_NUMBER
      - cd nginx-build-with-boringssl
      - sh ./require.sh
      - sh ./build.sh
      - cp -r debian nginx-1*/
      - cd nginx-1*
      - sudo dpkg-buildpackage -b -uc
      - cd ..
      - sudo chmod -R 777 nginx-1* *.deb
      - ls -alh *.deb
      - cp *.deb ../releases/$TRAVIS_JOB_NUMBER
      - sudo cp ./luajit2-*/src/libluajit.so /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
      - sudo ldconfig
      - ./nginx-1*/objs/nginx -V
      - file ./nginx-1*/objs/nginx
      - ldd ./nginx-1*/objs/nginx
      - cd ..
      deploy:
        <<: *s3