FROM debian:bookworm-slim

# ADD ./source.tar.gz /workspace
ADD .. /workspace

ENV CI=1
RUN apt-get update \
  && apt-get install -y fish unzip curl gawk wget git perl bison lsb-release \
    wget software-properties-common gnupg debhelper cmake pkg-config vim \
    --no-install-recommends \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && curl -sSL https://apt.llvm.org/llvm.sh | bash -s -- 18 \
  && curl -sSL https://git.io/g-install | sh -s -- fish bash -y \
  && bash /workspace/.github/nginx-package-build/get-deps.sh \
  && rm -r deps

WORKDIR /workspace

# docker build -t dev .
# docker run -v /opt:/opt --rm -it dev fish
